Internationalization
night-woods/przewodnik pull request #7
Opened 2022-01-08 16:59 UTC by karolstawowski

2022-01-08 17:05 UTC, karolstawowski commented on admin/components/Layout/Navigation.tsx
> +export const navigations = () => {
Aby móc użyć useTranslate w tablicy, przekształciłem ją w funkcję strzałkową, która zwraca tablicę poprzednio zdefiniowanych obiektów

2022-01-11 11:30 UTC, barnski requested changes

2022-01-11 11:30 UTC, barnski commented on admin/components/Layout/Navigation.tsx
> +  const { t } = useTranslation()
Dobry pomysł, jedna uwaga:
W Reactcie jest taka konwencja, żeby hooki wywoływać tylko w komponentach lub w customowych hookach. Customowe hooki to z grubsza zwykłe funkcje wywołujące inne hooki ;) 
Więcej: 

- https://reactjs.org/docs/hooks-rules.html
- https://reactjs.org/docs/hooks-custom.html

Zainstalowałem plugin do Eslinta, który sprawdza reguły zgodnie z dobrymi praktykami. Trzeba zmienić nazwę tej funkcji, żeby zaczynała się od "use" -> `useNavigation` albo `useRoutes` to moje propozycje

BTW ogólnie powiedziałbym, że dobrą praktyką jest używanie jakiegoś czasownika w nazwach funkcji.

2022-01-11 11:30 UTC, barnski commented on admin/components/Layout/DesktopSidebar.tsx
> +              <a
W tym momencie jak wejde na `/en-GB/locations` i klikne w ktorys z tych linkow to ląduję na polskiej wersji z powrotem.

Trzeba:
1. Trzeba tutaj otoczyc `a` komponentem `Link` i przeniesc href oraz key
2. W Linku uzyc locale zgodnie z https://github.com/vinissimus/next-translate#10-how-to-change-the-language

2022-01-11 11:30 UTC, barnski commented on admin/i18n.json
> +  "locales": ["pl", "en-GB"],
proponuje jako drugie locale wrzucic poki co "en" bedzie troche wygodniej mimo ze mniej precyzyjnie

2022-01-12 10:20 UTC, barnski approved these changes

2022-01-12 10:20 UTC, merged